/**
 * Path/macro helpers shared by project parsing and makefile generation.
 * Pure Node — no vscode imports.
 */
import * as path from 'path';

export function toPosix(p: string): string {
  return p.split('\\').join('/');
}

export function toNative(p: string): string {
  return path.sep === '\\' ? p.split('/').join('\\') : p;
}

/**
 * Resolve a linked-resource locationURI such as
 *   PARENT-1-PROJECT_LOC/SRC/Ld
 *   PROJECT_LOC/sub
 *   F:/absolute/path
 *   relative/name
 * against the project root directory.
 */
export function resolveLocationUri(projectRoot: string, uri: string): string {
  const u = uri.replace(/\\/g, '/').trim();
  const fileMatch = u.match(/^file:\/(.*)$/i);
  if (fileMatch) {
    // cross-drive absolute target (see makeLocationUri)
    return path.normalize(fileMatch[1].replace(/^\/+/, ''));
  }
  const parentMatch = u.match(/^PARENT-(\d+)-PROJECT_LOC(?:(\/.*))?$/);
  if (parentMatch) {
    const levels = Number(parentMatch[1]);
    const rest = parentMatch[2] ?? '';
    let base = projectRoot;
    for (let i = 0; i < levels; i++) {
      base = path.dirname(base);
    }
    return path.normalize(base + rest.replace(/\//g, path.sep));
  }
  if (/^PROJECT_LOC(?:(\/.*))?$/.test(u)) {
    const rest = u.replace(/^PROJECT_LOC/, '');
    return path.normalize(projectRoot + rest.replace(/\//g, path.sep));
  }
  if (path.isAbsolute(u)) {
    return path.normalize(u);
  }
  return path.normalize(path.join(projectRoot, u.replace(/\//g, path.sep)));
}

/**
 * Inverse of resolveLocationUri: express `target` relative to the project
 * root, using PARENT-N-PROJECT_LOC when the target lies above the root.
 */
export function makeLocationUri(projectRoot: string, target: string): string {
  const rel = path.relative(projectRoot, target);
  if (path.isAbsolute(rel)) {
    // different drive (Windows): path.relative returns an absolute path and
    // PARENT-N cannot express it — use a file URI
    return 'file:/' + toPosix(target).replace(/^\/+/, '');
  }
  if (!rel.startsWith('..')) {
    return toPosix(rel);
  }
  // count how many levels above
  let base = projectRoot;
  let levels = 0;
  while (levels < 32) {
    const r = path.relative(base, target);
    if (!r.startsWith('..')) {
      break;
    }
    base = path.dirname(base);
    levels++;
  }
  if (levels === 0) {
    return toPosix(target);
  }
  const rest = toPosix(path.relative(base, target));
  return `PARENT-${levels}-PROJECT_LOC${rest ? '/' + rest : ''}`;
}

/**
 * Convert a "logic path" from .cproject — e.g.
 *   ${workspace_loc:/${ProjName}/StdPeriphDriver/inc}
 *   "../"
 *   Ld/Link.ld
 * — into an absolute native path when it uses a workspace macro, an
 * absolute path, or starts with a linked-folder name. Plain relative paths
 * (like "../") return null so callers keep them verbatim, matching the
 * makefiles generated by MRS.
 */
export function convertLogicToFullPath(
  projectRoot: string,
  projectName: string,
  logicPath: string,
  linkedFolders: Map<string, string> // logic name -> absolute target dir
): string | null {
  if (!logicPath) return null;
  let p = logicPath.trim().replace(/^"(.*)"$/, '$1');

  const wsMacro = p.match(/^\$\{workspace_loc:\/?\$\{ProjName\}\/(.+)\}$/) || p.match(/^\$\{workspace_loc:\/(.+)\}$/);
  if (wsMacro) {
    return resolveSegs(projectRoot, projectName, wsMacro[1], linkedFolders);
  }
  if (/^\$\{workspace_loc:\/?\$\{ProjName\}\}$/.test(p) || p === '${workspace_loc:/}') {
    return projectRoot;
  }
  if (/^\$\{project\}(\/|$)/.test(p)) {
    return resolveSegs(projectRoot, projectName, p.replace(/^\$\{project\}\//, ''), linkedFolders);
  }
  if (p.includes('${ProjName}')) {
    return resolveSegs(projectRoot, projectName, p.split('${ProjName}').join(projectName), linkedFolders);
  }
  const norm = toPosix(p);
  if (path.isAbsolute(norm.replace(/\/$/, ''))) {
    return path.normalize(norm);
  }
  const segs = norm.split('/');
  const linked = linkedFolders.get(segs[0]);
  if (linked) {
    return path.normalize(path.join(linked, segs.slice(1).join('/')));
  }
  return null;
}

function resolveSegs(
  projectRoot: string,
  projectName: string,
  relPosix: string,
  linkedFolders: Map<string, string>
): string {
  const segs = toPosix(relPosix).split('/').filter((s) => s.length && s !== '.');
  const linked = linkedFolders.get(segs[0]);
  if (linked) {
    return path.normalize(path.join(linked, segs.slice(1).join('/')));
  }
  return path.normalize(path.join(projectRoot, segs.join('/')));
}
