/**
 * CDT-style makefile generator: writes makefile / sources.mk / objects.mk /
 * <dir>/subdir.mk into the build (config) directory. Byte-compatible with
 * the MounRiver Studio goldens of both generations (1.9.2 and 2.1.0; the
 * `blocksFirst` option selects the 2.x template layout — see the notes at
 * each branch). Also writes analysis data files when enabled.
 * Pure Node — no vscode imports.
 */
import * as fs from 'fs';
import * as path from 'path';
import { encodeArtifact } from './platformEncoding';
import { analysisFlags } from './analysis';
import { Cproject } from './cproject';
import { LogicDirMap, extGroups, scanSources } from './scan';
import { toPosix } from './macros';
import {
  assemblerOptions,
  cCompilerOptions,
  cppCompilerOptions,
  cLinkerOptions,
  cppLinkerOptions,
  commonOptions,
  listingOptions,
  objCopyOptions,
  flashExtensions,
  userObjects,
  userLibs,
  wchLibsOptions,
} from './flags';
import { ToolchainInfo } from './toolchain';

const RULE = '################################################################################\n';
const HEADER = (tool: string) => RULE + `# ${tool}\n# Automatically-generated file. Do not edit!\n` + RULE;

const POSIX = (p: string) => toPosix(p);
/** escape spaces for make */
const ESC = (p: string) => toPosix(p).split(' ').join('\\ ');

/** join a block: "VAR += \\\n a \\\n b \n\n" (last entry loses its backslash) */
function varBlock(name: string, entries: string[], crlfValues = false): string {
  if (!entries.length) return '';
  // 2.x goldens end every line (name, values) with CRLF; 1.x uses bare LF
  // for all of it. writeMk's post-processing turns `\` + LF back into a
  // continuation (bare LF), so the name/continuation lines must carry `\n`
  // here and get their CR from writeMk's first replace — matching goldens.
  const eol = crlfValues ? '\r\n' : '\n';
  let t = `${name} += \\${eol}`;
  for (const e of entries) {
    t += `${e} \\${eol}`;
  }
  return t.slice(0, t.lastIndexOf('\\')) + eol + eol;
}

export interface GenerateResult {
  files: string[];
  dirs: string[];
  sourceCount: number;
}

/** Reject any write target that escapes the build directory. */
function assertInsideBuildDir(buildDir: string, target: string): void {
  const resolved = path.resolve(target);
  const base = path.resolve(buildDir);
  if (resolved !== base && !resolved.startsWith(base + path.sep)) {
    throw new Error(`refusing to write outside build dir: ${resolved}`);
  }
}

export function generateMakefiles(
  cp: Cproject,
  tc: ToolchainInfo,
  opts: { headerTool?: string; analysis?: boolean; blocksFirst?: boolean } = {}
): GenerateResult {
  const buildDir = path.join(cp.projectRoot, cp.configName);
  fs.mkdirSync(buildDir, { recursive: true });
  const headerTool = opts.headerTool ?? 'Generated by mrs2-vscode';
  // older CDT generations (MRS 1.x goldens, e.g. HarmonyOS) emit each
  // *_DEPS block right after its *_SRCS; newer ones group OBJS between
  // all SRCS and all DEPS blocks
  // blocksFirst selects the 2.x template generation; it governs several
  // independent differences at once (EOL style, recipe @ prefix, DEPS
  // include order, head layout, all/main-build) — each branch documents
  // its own piece, so this single flag stays the only switch needed.
  const blocksFirst = opts.blocksFirst ?? false;

  const isCpp = cp.isCpp;
  const map: LogicDirMap = scanSources(cp);
  const dirsDesc = [...map.keys()].sort((a, b) => (a > b ? -1 : 1));
  const dirsAsc = [...map.keys()].sort((a, b) => (a > b ? 1 : -1));

  const target = cp.outputPrefix + cp.targetName;
  const compilerC = path.basename(tc.compilerC);
  const compilerCpp = path.basename(tc.compilerCpp);
  const linker = isCpp ? path.basename(tc.linkerCpp) : path.basename(tc.linkerC);
  const ar = tc.prefix + 'ar';
  const objcopy = path.basename(tc.objcopy);
  const objdump = path.basename(tc.objdump);
  const sizeTool = path.basename(tc.size);

  const common = commonOptions(cp, tc.name);
  // analysis builds add -fstack-usage (.su per function) and
  // -fdump-rtl-expand (call dumps) to every compile line
  const extra = opts.analysis ? ' ' + analysisFlags().join(' ') : '';
  const cOpts = cCompilerOptions(cp) + extra;
  const cppOpts = cppCompilerOptions(cp) + extra;
  const asmOpts = assemblerOptions(cp) + extra;
  const ldOpts = isCpp ? cppLinkerOptions(cp) : cLinkerOptions(cp);
  const userObjs = userObjects(cp);
  const libs = userLibs(cp);
  const wchLibs = wchLibsOptions(cp, tc.name);

  const written: string[] = [];
  let sourceCount = 0;

  const writeMk = (rel: string, content: string) => {
    const base = path.resolve(buildDir);
    const file = path.resolve(base, rel);
    if (file !== base && !file.startsWith(base + path.sep)) {
      throw new Error(`refusing to write outside build dir: ${file}`);
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    // MRS makefiles use CRLF everywhere EXCEPT backslash continuation
    // lines, which end with a bare LF. Reproduce that mix byte-for-byte.
    const native = blocksFirst
      ? content.replace(/\n/g, '\r\n') // 2.x goldens are pure CRLF (no bare-LF continuations)
      : content.replace(/\n/g, '\r\n').replace(/\\\r\n/g, '\\\n');
    // make/gcc read these files through the ANSI code page (GBK on Chinese
    // Windows): UTF-8 bytes in a non-ASCII project path turn to mojibake and
    // every #include fails with "No such file or directory" (MRS2 writes
    // them in the platform encoding for the same reason). GBK is an ASCII
    // superset — pure-ASCII content stays byte-identical.
    fs.writeFileSync(file, encodeArtifact(native));
    written.push(file);
  };

  const groups = extGroups(isCpp);
  const recipeFor = (g: (typeof groups)[number]): string => {
    const compiler = g.isCppFile ? compilerCpp : compilerC;
    const toolOpts = g.isAsm ? asmOpts : g.isCppFile ? cppOpts : cOpts;
    if (blocksFirst) {
      // 2.x goldens: recipe prefixed with a single @ + tab, and
      // -fmax-errors=20 sits between the save-restore flag and the --param
      // options (before the per-tool options); tail line is a bare @
      const maxErrors = ' -fmax-errors=20';
      const common2 = common.replace(' -mno-save-restore', ' -mno-save-restore' + maxErrors);
      return `\t@\t${compiler}${common2}${toolOpts} -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"\n\t@\n`;
    }
    return `\t@\t@\t${compiler}${common}${toolOpts} -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"\n\t@\t@\n`;
  };

  // ---------------- subdir.mk per logic dir (descending order) ----------------
  for (const dir of dirsDesc) {
    const files = map.get(dir)!;
    sourceCount += files.length;

    const firstRealDir = path.posix.dirname(files[0].fullpath);
    const projPosix = toPosix(cp.projectRoot);
    const isExternal = !(firstRealDir + '/').startsWith(projPosix + '/');

    let body =
      HEADER(headerTool) +
      '\n' +
      '# Add inputs and outputs from these tool invocations to the build variables \n';

    let vars = '';
    // CDT emits two block orders across its generations: newer projects
    // interleave DEPS right after each SRCS group; older ones put all
    // *_SRCS first, then OBJS, then all *_DEPS. make is indifferent, but
    // the byte-compare against the golden build is not.
    if (blocksFirst) {
      for (const g of groups) {
        const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
        if (!group.length) continue;
        const srcs = group.map((f) => ESC(isExternal ? f.fullpath : path.posix.join('..', f.logicName)));
        vars += varBlock(`${g.variable}_SRCS`, srcs);
        vars += varBlock(
          `${g.variable}_DEPS`,
          group.map((f) => `./${ESC(stripExt(f.logicName))}.d`)
        );
      }
      vars += varBlock(
        'OBJS',
        files.map((f) => `./${ESC(stripExt(f.logicName))}.o`)
      );
    } else {
      for (const g of groups) {
        const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
        if (!group.length) continue;
        const srcs = group.map((f) => ESC(isExternal ? f.fullpath : path.posix.join('..', f.logicName)));
        vars += varBlock(`${g.variable}_SRCS`, srcs);
      }
      vars += varBlock(
        'OBJS',
        files.map((f) => `./${ESC(stripExt(f.logicName))}.o`)
      );
      for (const g of [...groups].reverse()) {
        const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
        if (!group.length) continue;
        vars += varBlock(
          `${g.variable}_DEPS`,
          group.map((f) => `./${ESC(stripExt(f.logicName))}.d`)
        );
      }
    }

    let rules = '';
    for (const g of groups) {
      const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
      if (!group.length) continue;
      if (isExternal) {
        for (const f of group) {
          const base = path.posix.basename(stripExt(f.logicName));
          const obj = dir ? `${dir}/${base}.o` : `${base}.o`;
          rules += `${obj}: ${POSIX(f.fullpath)}\n${recipeFor(g)}`;
        }
      } else {
        const prereqDir = ESC(path.posix.normalize(path.posix.join('..', dir)));
        const pat = dir ? `${dir}/%.o: ${prereqDir}/%.${g.ext}` : `%.o: ${prereqDir}/%.${g.ext}`;
        rules += `${pat}\n${recipeFor(g)}`;
        for (const f of group) {
          if (f.logicName.includes(' ')) {
            rules += `${ESC(stripExt(f.logicName))}.o: ${ESC(path.posix.join('..', f.logicName))}\n${recipeFor(g)}`;
          }
        }
      }
    }
    if (rules.length) {
      rules += '\n';
    }

    // 2.x goldens put two blank lines between the vars and the comment
    body += vars + (blocksFirst ? '\n\n' : '\n') + '# Each subdirectory must supply rules for building sources it contributes\n' + rules;
    writeMk(path.posix.join(dir, 'subdir.mk'), body);
  }

  // ---------------- objects.mk ----------------
  {
    let t = HEADER(headerTool) + '\n';
    t += 'USER_OBJS :=';
    for (const o of userObjs) {
      // unquoted: this make port mis-parses quoted absolute paths ("F:\...")
      // on the expanded target line (drive-letter colon heuristic fails)
      t += ` ${ESC(o)}`;
    }
    t += '\n\nLIBS :=';
    if (cp.artifactType === 'exe') {
      for (const lib of libs) {
        t += ` -l${lib}`;
      }
      t += wchLibs;
    }
    t += '\n\n';
    writeMk('objects.mk', t);
  }

  // ---------------- sources.mk ----------------
  {
    const flashVar = cp.createFlash && cp.artifactType === 'exe';
    const listVar = cp.createListing && cp.artifactType === 'exe';
    const sizeVar = cp.printSize && cp.artifactType === 'exe';
    const initVars = [
      'ELF_SRCS',
      'OBJ_SRCS',
      'S_SRCS',
      'ASM_UPPER_SRCS',
      'ASM_SRCS',
      ...(isCpp ? ['C_UPPER_SRCS', 'CPP_SRCS', 'CXX_SRCS', 'C++_SRCS', 'CC_SRCS'] : []),
      'C_SRCS',
      'S_UPPER_SRCS',
      'O_SRCS',
      'ASM_UPPER_DEPS',
      'OBJS',
      ...(flashVar ? ['SECONDARY_FLASH'] : []),
      ...(listVar ? ['SECONDARY_LIST'] : []),
      ...(sizeVar ? ['SECONDARY_SIZE'] : []),
      'ASM_DEPS',
      'S_DEPS',
      'S_UPPER_DEPS',
      'C_DEPS',
      ...(isCpp ? ['C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS'] : []),
    ];
    let t = HEADER(headerTool) + '\n';
    for (const v of initVars) {
      t += `${v} := \n`;
    }
    t += '\n# Every subdirectory with source files must be described here\nSUBDIRS := \\\n';
    for (const d of dirsAsc) {
      t += `${POSIX(d)} \\\n`;
    }
    t += '\n';
    writeMk('sources.mk', t);
  }

  // ---------------- main makefile ----------------
  {
    const isExe = cp.artifactType === 'exe';
    const flashExts = flashExtensions(cp);
    const flashVar = isExe && cp.createFlash;
    const listVar = isExe && cp.createListing;
    const sizeVar = isExe && cp.printSize;
    const hasSecondaries = flashVar || listVar || sizeVar;

    // 2.x generation orders the DEPS includes S_DEPS-first; 1.x leads with
    // the assembler variants (both goldens matched respectively)
    const depVars = blocksFirst
      ? isCpp
        ? ['S_DEPS', 'S_UPPER_DEPS', 'ASM_DEPS', 'ASM_UPPER_DEPS', 'C_DEPS', 'C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS']
        : ['S_DEPS', 'S_UPPER_DEPS', 'ASM_DEPS', 'ASM_UPPER_DEPS', 'C_DEPS']
      : isCpp
        ? ['ASM_UPPER_DEPS', 'ASM_DEPS', 'S_DEPS', 'S_UPPER_DEPS', 'C_DEPS', 'C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS']
        : ['ASM_UPPER_DEPS', 'ASM_DEPS', 'S_DEPS', 'S_UPPER_DEPS', 'C_DEPS'];

    // head layout differs by generation: 1.9.2 has a blank line after the
    // header; 2.1.0 does not (the `RM :=` gap is a plain newline in both)
    const headGap = blocksFirst ? '' : '\n';
    let t =
      HEADER(headerTool) +
      headGap +
      '-include ../makefile.init\n' +
      '\n' +
      'RM := rm -rf\n' +
      '\n' +
      '# All of the sources participating in the build are defined here\n' +
      '-include sources.mk\n';
    for (const d of dirsDesc) {
      t += d ? `-include ${POSIX(d)}/subdir.mk\n` : '-include subdir.mk\n';
    }
    // the root dir ('' sorts last descending) already emitted its include
    // above — only add it when the project has no root-level sources
    if (!map.has('')) t += '-include subdir.mk\n';
    t += '-include objects.mk\n\n';
    t += 'ifneq ($(MAKECMDGOALS),clean)\n';
    for (const v of depVars) {
      t += `ifneq ($(strip $(${v})),)\n-include $(${v})\nendif\n`;
    }
    t += 'endif\n\n-include ../makefile.defs\n\n';

    if (hasSecondaries) {
      t += '# Add inputs and outputs from these tool invocations to the build variables \n';
      if (flashVar) {
        t += 'SECONDARY_FLASH += \\\n';
        for (const ext of flashExts) {
          t += `${target}.${ext} \\\n`;
        }
        t += '\n';
      }
      if (listVar) t += `SECONDARY_LIST += \\\n${target}.lst \\\n\n`;
      if (sizeVar) t += `SECONDARY_SIZE += \\\n${target}.siz \\\n\n`;
    }

    const elfExt = cp.artifactExtension || 'elf';
    const elfTarget = `${target}.${elfExt}`;
    const pre = cp.prebuildStep.trim();
    const post = cp.postbuildStep.trim();
    if (blocksFirst) {
      // MRS 2.x generation: `all` delegates to a main-build sub-target via a
      // recursive make call (CDT's newer all/main-build template); the
      // recipe line carries a trailing space and the header blank line
      // doubles, matching the 2.1.0 goldens
      t += `\n# All Target\nall: \n\t\$(MAKE) --no-print-directory main-build \n`;
      t += `\nmain-build: ${elfTarget}${hasSecondaries ? ' secondary-outputs' : ''}\n`;
    } else {
      // MRS 1.x generation: `all` hangs directly off the elf
      t += `\n# All Target\nall: ${elfTarget}${hasSecondaries ? ' secondary-outputs' : ''}\n`;
    }
    if (pre) t += `\t-@echo Executing pre-build steps\n\t-${pre}\n`;
    if (post) t += `\t-@echo Executing post-build steps\n\t-${post}\n`;
    t += `\n# Tool invocations\n`;

    if (isExe) {
      t += `${elfTarget}: $(OBJS) $(USER_OBJS)\n`;
      t += `\t@\t@\t${linker}${common}${ldOpts} -o "${elfTarget}" $(OBJS) $(USER_OBJS) $(LIBS)\n`;
      t += `\t@\t@\n`;
      if (flashVar) {
        const copyOpts = objCopyOptions(cp);
        for (const ext of flashExts) {
          const objcopyFlag = ext === 'bin' ? '-O binary' : '-O ihex';
          t += `${target}.${ext}: ${elfTarget}\n`;
          t += `\t@\t${objcopy} ${objcopyFlag}${copyOpts} "${elfTarget}"  "${target}.${ext}"\n`;
          t += `\t@\t@\n`;
        }
      }
      if (listVar) {
        t += `${target}.lst: ${elfTarget}\n`;
        t += `\t@\t${objdump}${listingOptions(cp)} "${elfTarget}" > "${target}.lst"\n`;
        t += `\t@\t@\n`;
      }
      if (sizeVar) {
        const fmt = cp.optionEnum('printsize.format') ?? 'berkeley';
        let szFlags = `--format=${fmt}`;
        if (cp.optionBool('printsize.hex')) szFlags += ' -x';
        if (cp.optionBool('printsize.totals')) szFlags += ' --totals';
        const szOther = cp.optionValue('printsize.other')?.trim();
        if (szOther) szFlags += ` ${szOther}`;
        t += `${target}.siz: ${elfTarget}\n`;
        t += `\t@\t${sizeTool} ${szFlags} "${elfTarget}"\n`;
        t += `\t@\t@\n`;
      }
    } else {
      t += `${target}.a: $(OBJS) $(USER_OBJS)\n`;
      t += `\t@\t@\t${ar} -cr "${target}.a" $(OBJS) $(USER_OBJS)\n`;
      t += `\t@\t@\n`;
    }

    // C projects: byte-identical to the MRS2 golden clean line; C++ adds
    // the C++ dep-file variables the golden C order never had
    const cleanVars = isCpp
      ? '$(ASM_UPPER_DEPS)$(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(C_UPPER_DEPS)$(CPP_DEPS)$(CXX_DEPS)$(CC_DEPS)$(C++_DEPS)'
      : '$(ASM_UPPER_DEPS)$(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS)';
    t += `# Other Targets\nclean:\n\t-$(RM) ${cleanVars} ${target}.${isExe ? elfExt : 'a'}\n\t-@\n`;
    if (hasSecondaries) {
      const secs = [
        flashVar ? '$(SECONDARY_FLASH)' : '',
        listVar ? '$(SECONDARY_LIST)' : '',
        sizeVar ? '$(SECONDARY_SIZE)' : '',
      ].filter(Boolean);
      t += `secondary-outputs: ${secs.join(' ')}\n`;
    }
    t += `\n.PHONY: all clean dependents\n\n-include ../makefile.targets\n`;
    writeMk('makefile', t);
  }

  return { files: written, dirs: dirsAsc, sourceCount };
}

function stripExt(logicName: string): string {
  const slash = logicName.lastIndexOf('/');
  const dot = logicName.lastIndexOf('.');
  if (dot > slash) return logicName.slice(0, dot);
  return logicName;
}
