/**
 * CDT-style makefile generator: writes makefile / sources.mk / objects.mk /
 * <dir>/subdir.mk into the build (config) directory. Byte-compatible with
 * the MounRiver Studio goldens of both generations (2.1.0 by default at
 * runtime; pass `mrs2Style: false` for the legacy 1.9.2 layout — golden
 * checks do). Also writes analysis data files when enabled.
 * Pure Node — no vscode imports.
 */
import * as fs from 'fs';
import * as path from 'path';
import { encodeArtifact } from './platformEncoding';
import { analysisFlags } from './analysis';
import { Cproject } from './cproject';
import { LogicDirMap, extGroups, scanSources } from './scan';
import { toPosix, resolveLocationUri } from './macros';
import {
  assemblerOptions,
  cCompilerOptions,
  cppCompilerOptions,
  cLinkerOptions,
  cppLinkerOptions,
  commonOptions,
  listingOptions,
  objCopyOptions,
  flashExtensions,
  userObjects,
  userLibs,
  wchLibsOptions,
} from './flags';
import { ToolchainInfo } from './toolchain';

const RULE = '################################################################################\n';
const HEADER = (tool: string) => RULE + `# ${tool}\n# Automatically-generated file. Do not edit!\n` + RULE;

const POSIX = (p: string) => toPosix(p);
/** escape spaces for make */
const ESC = (p: string) => toPosix(p).replace(/\$/g, '$$$$').split(' ').join('\\ ');

/**
 * Escape a literal `$` for the makefile level, leaving make-syntax tokens
 * alone. make expands `$x` sequences itself before the shell ever sees the
 * recipe line, so a user-supplied `$` (an -I/-L/-T/-D path, a macro value)
 * must be doubled for make to emit one real dollar. Tokens that are make
 * syntax rather than user text must survive verbatim:
 *   automatic variables   $@ (the .o being built), $<, $^, $*, $?
 *   variable references   $(VAR) / ${VAR} written in user option text
 * CDT's listing flag -Wa,-adhlns="$@.lst" is the case that matters: it
 * names the .lst after `$@`, and doubling it to `$$@` makes the shell see
 * an empty `$@`, so every listing silently collapses onto a bare ".lst"
 * (and the bytes stop matching MRS2's single-$ output).
 */
export function escapeMakeDollars(s: string): string {
  return s.replace(/\$(?![<@^*?({])/g, '$$$$');
}

/** join a block: "VAR += \\\n a \\\n b \n\n" (last entry loses its backslash) */
function varBlock(name: string, entries: string[], crlfValues = false): string {
  if (!entries.length) return '';
  // 2.x goldens end every line (name, values) with CRLF; 1.x uses bare LF
  // for all of it. writeMk's post-processing turns `\` + LF back into a
  // continuation (bare LF), so the name/continuation lines must carry `\n`
  // here and get their CR from writeMk's first replace — matching goldens.
  const eol = crlfValues ? '\r\n' : '\n';
  let t = `${name} += \\${eol}`;
  for (const e of entries) {
    t += `${e} \\${eol}`;
  }
  return t.slice(0, t.lastIndexOf('\\')) + eol + eol;
}

export interface GenerateResult {
  files: string[];
  dirs: string[];
  sourceCount: number;
}

/** Reject any write target that escapes the build directory. */
function assertInsideBuildDir(buildDir: string, target: string): void {
  const resolved = path.resolve(target);
  const base = path.resolve(buildDir);
  if (resolved !== base && !resolved.startsWith(base + path.sep)) {
    throw new Error(`refusing to write outside build dir: ${resolved}`);
  }
}

export function generateMakefiles(
  cp: Cproject,
  tc: ToolchainInfo,
  opts: { headerTool?: string; analysis?: boolean; mrs2Style?: boolean } = {}
): GenerateResult {
  const buildDir = path.join(cp.projectRoot, cp.configName);
  fs.mkdirSync(buildDir, { recursive: true });
  // make cannot express these characters anywhere in its syntax — "(" and ")"
  // are archive/member syntax, ";" starts an inline recipe, "%" is the
  // pattern wildcard, "#" starts a comment (make does not know shell quotes).
  // Fail up front with an actionable message instead of make's cryptic
  // "No rule to make target" later. (MRS2 generates byte-identical syntax and
  // fails the same way.)
  const hostile = /[();%#]/;
  const checkHostile = (p: string): void => {
    if (hostile.test(p)) {
      throw new Error(
        `Project path contains a character that a makefile cannot express ("(", ")", ";", "%", "#"): "${p}" — ` +
        `rename the folder or move the project to a path without it.`
      );
    }
  };
  checkHostile(cp.projectRoot);
  for (const loc of cp.linkedFolders.values()) {
    checkHostile(resolveLocationUri(cp.projectRoot, loc));
  }
  const headerTool = opts.headerTool ?? 'Generated by mrvc';
  // older CDT generations (MRS 1.x goldens, e.g. HarmonyOS) emit each
  // *_DEPS block right after its *_SRCS; newer ones group OBJS between
  // all SRCS and all DEPS blocks
  // mrs2Style selects the MRS2 2.x template generation and is the RUNTIME
  // DEFAULT (MRS 1.9.2 is end-of-life); it governs several
  // independent differences at once (EOL style, recipe @ prefix, DEPS
  // include order, head layout, all/main-build) — each branch documents
  // its own piece, so this single flag stays the only switch needed.
  // Pass false only to reproduce the legacy 1.9.2 layout (golden checks).
  const mrs2Style = opts.mrs2Style ?? true;

  const isCpp = cp.isCpp;
  const map: LogicDirMap = scanSources(cp);
  const dirsDesc = [...map.keys()].sort((a, b) => (a > b ? -1 : 1));
  const dirsAsc = [...map.keys()].sort((a, b) => (a > b ? 1 : -1));

  const target = cp.outputPrefix + cp.targetName;
  const compilerC = path.basename(tc.compilerC);
  const compilerCpp = path.basename(tc.compilerCpp);
  const linker = isCpp ? path.basename(tc.linkerCpp) : path.basename(tc.linkerC);
  const ar = tc.prefix + 'ar';
  const objcopy = path.basename(tc.objcopy);
  const objdump = path.basename(tc.objdump);
  const sizeTool = path.basename(tc.size);

  const style = mrs2Style ? ('2x' as const) : ('1x' as const);
  const escMakeDollars = escapeMakeDollars;
  // analysis builds add -fstack-usage (.su per function) and -fdump-rtl-expand
  // (call dumps) to every compile line. MRS2 emits the dump flag right after
  // `-fmax-errors=20` in the target-flag section — in the 2.x style it joins
  // `common` there instead of the per-tool options tail; the 1.x style keeps
  // the pre-2.x behavior of putting both flags on the per-tool tail (no 1.x
  // oracle for analysis, unchanged since 0.1.4).
  const analysisAll = opts.analysis ? analysisFlags() : [];
  const dumpFlag = analysisAll.find((f) => f.startsWith('-fdump')) ?? '';
  const tailFlags = analysisAll.filter((f) => !f.startsWith('-fdump') || style === '1x');
  // commonOptions carries the user's target/optimization/warnings/debugging
  // "other" free text — same `$`-escaping contract as the per-tool option
  // strings below (a bare `$` would be eaten by make as a variable)
  let common = escMakeDollars(commonOptions(cp, tc.name, style));
  if (dumpFlag && style === '2x') {
    common = common.replace(' -fmax-errors=20', ` -fmax-errors=20 ${dumpFlag}`);
  }
  const extra = tailFlags.length ? ` ${tailFlags.join(' ')}` : '';
  // per-tool option strings go through escMakeDollars (see its comment):
  // user `$` escaped, make tokens ($@/$(VAR)) preserved. The analysis tail
  // is appended AFTER escaping so its own text stays engine-generated.
  const cOpts = escMakeDollars(cCompilerOptions(cp, false, style)) + extra;
  const cppOpts = escMakeDollars(cppCompilerOptions(cp, false, style)) + extra;
  const asmOpts = escMakeDollars(assemblerOptions(cp, false, style)) + extra;
  const ldOpts = isCpp
    ? escMakeDollars(cppLinkerOptions(cp, style, buildDir))
    : escMakeDollars(cLinkerOptions(cp, style, buildDir));
  const userObjs = userObjects(cp);
  const libs = userLibs(cp);
  const wchLibs = wchLibsOptions(cp, tc.name);

  const written: string[] = [];
  let sourceCount = 0;

  const writeMk = (rel: string, content: string) => {
    const base = path.resolve(buildDir);
    const file = path.resolve(base, rel);
    if (file !== base && !file.startsWith(base + path.sep)) {
      throw new Error(`refusing to write outside build dir: ${file}`);
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    // MRS makefiles use CRLF everywhere EXCEPT backslash continuation
    // lines, which end with a bare LF. Reproduce that mix byte-for-byte.
    // 2.x additionally lowercases every drive letter (golden: "f:/..." /
    // "f:\..." everywhere) — the letter must start a token (preceded by
    // whitespace/a quote/an assignment/end of line), otherwise .PHONY: would
    // become .PHONy:. Known limitation: glued paths like `-LF:/lib` or
    // `-Wl,-Map,F:/m.map` are NOT converted (no such form in any golden);
    // if a future .cproject emits one, the 2.x byte-compare will flag it.
    const lowerDrives = (s: string): string =>
      s.replace(/(^|[\s"'=])([A-Za-z]):/g, (_m, pre: string, drv: string) => pre + drv.toLowerCase() + ':');
    const native = mrs2Style
      ? lowerDrives(content).replace(/\n/g, '\r\n')
      : content.replace(/\n/g, '\r\n').replace(/\\\r\n/g, '\\\n');
    // make/gcc read these files through the ANSI code page (GBK on Chinese
    // Windows): UTF-8 bytes in a non-ASCII project path turn to mojibake and
    // every #include fails with "No such file or directory" (MRS2 writes
    // them in the platform encoding for the same reason). GBK is an ASCII
    // superset — pure-ASCII content stays byte-identical.
    fs.writeFileSync(file, encodeArtifact(native));
    written.push(file);
  };

  const groups = extGroups(isCpp);
  const recipeFor = (g: (typeof groups)[number]): string => {
    const compiler = g.isCppFile ? compilerCpp : compilerC;
    const toolOpts = g.isAsm ? asmOpts : g.isCppFile ? cppOpts : cOpts;
    if (mrs2Style) {
      // 2.x goldens: single @ prefix and NO tail line — `common` (built in
      // the 2.x style) already carries -fmax-errors=20 and the verbatim
      // target.other spacing
      return `\t@\t${compiler}${common}${toolOpts} -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"\n`;
    }
    return `\t@\t@\t${compiler}${common}${toolOpts} -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"\n\t@\t@\n`;
  };

  // ---------------- subdir.mk per logic dir (descending order) ----------------
  for (const dir of dirsDesc) {
    const files = map.get(dir)!;
    sourceCount += files.length;

    const projPosix = toPosix(cp.projectRoot);
    // a logic dir can MIX real and linked-out files (a hand-written .project
    // may link a target under the same name as a real folder — the CDT UI
    // refuses, the XML doesn't): judging by the first file only put the dir
    // on the pattern rule `dir/%.o: ../dir/%.ext`, which then targeted a
    // nonexistent ../dir for the external members (or vice versa). ANY
    // external member forces the per-file rules, which are correct for
    // every file regardless of where it lives.
    const isExternal = files.some((f) => !(path.posix.dirname(f.fullpath) + '/').startsWith(projPosix + '/'));

    let body =
      HEADER(headerTool) +
      '\n' +
      '# Add inputs and outputs from these tool invocations to the build variables \n';

    let vars = '';
    // CDT emits two block orders across its generations: newer projects
    // interleave DEPS right after each SRCS group; older ones put all
    // *_SRCS first, then OBJS, then all *_DEPS. make is indifferent, but
    // the byte-compare against the golden build is not.
    if (mrs2Style) {
      for (const g of groups) {
        const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
        if (!group.length) continue;
        const srcs = group.map((f) => ESC(isExternal ? f.fullpath : path.posix.join('..', f.logicName)));
        vars += varBlock(`${g.variable}_SRCS`, srcs);
        vars += varBlock(
          `${g.variable}_DEPS`,
          group.map((f) => `./${ESC(stripExt(f.logicName))}.d`)
        );
      }
      vars += varBlock(
        'OBJS',
        files.map((f) => `./${ESC(stripExt(f.logicName))}.o`)
      );
    } else {
      for (const g of groups) {
        const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
        if (!group.length) continue;
        const srcs = group.map((f) => ESC(isExternal ? f.fullpath : path.posix.join('..', f.logicName)));
        vars += varBlock(`${g.variable}_SRCS`, srcs);
      }
      vars += varBlock(
        'OBJS',
        files.map((f) => `./${ESC(stripExt(f.logicName))}.o`)
      );
      for (const g of [...groups].reverse()) {
        const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
        if (!group.length) continue;
        vars += varBlock(
          `${g.variable}_DEPS`,
          group.map((f) => `./${ESC(stripExt(f.logicName))}.d`)
        );
      }
    }

    let rules = '';
    for (const g of groups) {
      const group = files.filter((f) => f.logicName.endsWith('.' + g.ext));
      if (!group.length) continue;
      if (isExternal) {
        for (const f of group) {
          const base = path.posix.basename(stripExt(f.logicName));
          const obj = dir ? `${dir}/${base}.o` : `${base}.o`;
          // ESC the prereq: external linked trees may contain spaces (an
          // unescaped space splits the prerequisite list); `$` doubles to
          // keep make from reading it as a variable reference. Paths without
          // either are byte-identical to the goldens.
          rules += `${ESC(obj)}: ${ESC(f.fullpath)}\n${recipeFor(g)}`;
        }
      } else {
        const prereqDir = ESC(path.posix.normalize(path.posix.join('..', dir)));
        const pat = dir ? `${dir}/%.o: ${prereqDir}/%.${g.ext}` : `%.o: ${prereqDir}/%.${g.ext}`;
        rules += `${pat}\n${recipeFor(g)}`;
        for (const f of group) {
          if (f.logicName.includes(' ')) {
            rules += `${ESC(stripExt(f.logicName))}.o: ${ESC(path.posix.join('..', f.logicName))}\n${recipeFor(g)}`;
          }
        }
      }
    }
    if (rules.length) {
      // 1.x always separates the rules block from the file end with a blank
      // line; the 2.x golden does so only for external-source directories
      // (per-file rules — the StdPeriphDriver golden ends with a blank line
      // while every in-project subdir ends right after its recipe)
      if (!mrs2Style || isExternal) rules += '\n';
    }

    // 2.x goldens put two blank lines between the vars and the comment
    body += vars + (mrs2Style ? '\n\n' : '\n') + '# Each subdirectory must supply rules for building sources it contributes\n' + rules;
    writeMk(path.posix.join(dir, 'subdir.mk'), body);
  }

  // ---------------- objects.mk ----------------
  {
    // 2.x golden: no blank line after the header and no trailing newline —
    // the file ends right after the LIBS line
    let t = HEADER(headerTool) + (mrs2Style ? '' : '\n');
    t += 'USER_OBJS :=';
    for (const o of userObjs) {
      // unquoted: this make port mis-parses quoted absolute paths ("F:\...")
      // on the expanded target line (drive-letter colon heuristic fails)
      t += ` ${ESC(o)}`;
    }
    t += '\n\nLIBS :=';
    if (cp.artifactType === 'exe') {
      for (const lib of libs) {
        t += ` -l${lib}`;
      }
      t += wchLibs;
    }
    if (!mrs2Style) t += '\n\n';
    writeMk('objects.mk', t);
  }

  // ---------------- sources.mk ----------------
  {
    const flashVar = cp.createFlash && cp.artifactType === 'exe';
    const listVar = cp.createListing && cp.artifactType === 'exe';
    const sizeVar = cp.printSize && cp.artifactType === 'exe';
    // 2.x golden declares the dep groups first, then OBJS, then the source
    // groups, then the SECONDARY markers, with no space after `:=`; 1.x
    // leads with the source groups and pads `:= ` (both goldens matched)
    const initVars = mrs2Style
      ? [
          'S_DEPS',
          'S_UPPER_DEPS',
          'ASM_DEPS',
          'ASM_UPPER_DEPS',
          'C_DEPS',
          ...(isCpp ? ['C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS'] : []),
          'OBJS',
          'ELF_SRCS',
          'OBJ_SRCS',
          'O_SRCS',
          'S_SRCS',
          'S_UPPER_SRCS',
          'ASM_SRCS',
          'ASM_UPPER_SRCS',
          'C_SRCS',
          ...(isCpp ? ['C_UPPER_SRCS', 'CPP_SRCS', 'CXX_SRCS', 'C++_SRCS', 'CC_SRCS'] : []),
          ...(flashVar ? ['SECONDARY_FLASH'] : []),
          ...(listVar ? ['SECONDARY_LIST'] : []),
          ...(sizeVar ? ['SECONDARY_SIZE'] : []),
        ]
      : [
          'ELF_SRCS',
          'OBJ_SRCS',
          'S_SRCS',
          'ASM_UPPER_SRCS',
          'ASM_SRCS',
          ...(isCpp ? ['C_UPPER_SRCS', 'CPP_SRCS', 'CXX_SRCS', 'C++_SRCS', 'CC_SRCS'] : []),
          'C_SRCS',
          'S_UPPER_SRCS',
          'O_SRCS',
          'ASM_UPPER_DEPS',
          'OBJS',
          ...(flashVar ? ['SECONDARY_FLASH'] : []),
          ...(listVar ? ['SECONDARY_LIST'] : []),
          ...(sizeVar ? ['SECONDARY_SIZE'] : []),
          'ASM_DEPS',
          'S_DEPS',
          'S_UPPER_DEPS',
          'C_DEPS',
          ...(isCpp ? ['C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS'] : []),
        ];
    let t = HEADER(headerTool) + '\n';
    for (const v of initVars) {
      t += mrs2Style ? `${v} :=\n` : `${v} := \n`;
    }
    t += '\n# Every subdirectory with source files must be described here\nSUBDIRS := \\\n';
    for (const d of dirsAsc) {
      t += `${POSIX(d)} \\\n`;
    }
    // 2.x golden ends right after the last SUBDIRS entry (no blank line)
    if (!mrs2Style) t += '\n';
    writeMk('sources.mk', t);
  }

  // ---------------- main makefile ----------------
  {
    const isExe = cp.artifactType === 'exe';
    const flashExts = flashExtensions(cp);
    const flashVar = isExe && cp.createFlash;
    const listVar = isExe && cp.createListing;
    const sizeVar = isExe && cp.printSize;
    const hasSecondaries = flashVar || listVar || sizeVar;

    // 2.x generation orders the DEPS includes S_DEPS-first; 1.x leads with
    // the assembler variants (both goldens matched respectively)
    const depVars = mrs2Style
      ? isCpp
        ? ['S_DEPS', 'S_UPPER_DEPS', 'ASM_DEPS', 'ASM_UPPER_DEPS', 'C_DEPS', 'C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS']
        : ['S_DEPS', 'S_UPPER_DEPS', 'ASM_DEPS', 'ASM_UPPER_DEPS', 'C_DEPS']
      : isCpp
        ? ['ASM_UPPER_DEPS', 'ASM_DEPS', 'S_DEPS', 'S_UPPER_DEPS', 'C_DEPS', 'C_UPPER_DEPS', 'CPP_DEPS', 'CXX_DEPS', 'CC_DEPS', 'C++_DEPS']
        : ['ASM_UPPER_DEPS', 'ASM_DEPS', 'S_DEPS', 'S_UPPER_DEPS', 'C_DEPS'];

    // head layout differs by generation: 1.9.2 has a blank line after the
    // header; 2.1.0 does not (the `RM :=` gap is a plain newline in both)
    const headGap = mrs2Style ? '' : '\n';
    let t =
      HEADER(headerTool) +
      headGap +
      '-include ../makefile.init\n' +
      '\n' +
      'RM := rm -rf\n' +
      '\n' +
      '# All of the sources participating in the build are defined here\n' +
      '-include sources.mk\n';
    for (const d of dirsDesc) {
      t += d ? `-include ${POSIX(d)}/subdir.mk\n` : '-include subdir.mk\n';
    }
    // the root dir ('' sorts last descending) already emitted its include
    // above — only add it when the project has no root-level sources
    if (!map.has('')) t += '-include subdir.mk\n';
    t += '-include objects.mk\n\n';
    t += 'ifneq ($(MAKECMDGOALS),clean)\n';
    for (const v of depVars) {
      t += `ifneq ($(strip $(${v})),)\n-include $(${v})\nendif\n`;
    }
    t += 'endif\n\n-include ../makefile.defs\n\n';

    if (hasSecondaries) {
      t += '# Add inputs and outputs from these tool invocations to the build variables \n';
      if (flashVar) {
        t += 'SECONDARY_FLASH += \\\n';
        for (const ext of flashExts) {
          t += `${target}.${ext} \\\n`;
        }
        t += '\n';
      }
      if (listVar) t += `SECONDARY_LIST += \\\n${target}.lst \\\n\n`;
      if (sizeVar) t += `SECONDARY_SIZE += \\\n${target}.siz \\\n\n`;
    }

    const elfExt = cp.artifactExtension || 'elf';
    const elfTarget = `${target}.${elfExt}`;
    const pre = cp.prebuildStep.trim();
    const post = cp.postbuildStep.trim();
    if (mrs2Style) {
      // MRS 2.x generation: `all` delegates to a main-build sub-target via a
      // recursive make call (CDT's newer all/main-build template); the
      // recipe line carries a trailing space and the header blank line
      // doubles, matching the 2.1.0 goldens
      t += `\n# All Target\nall: \n\t\$(MAKE) --no-print-directory main-build \n`;
      t += `\nmain-build: ${elfTarget}${hasSecondaries ? ' secondary-outputs' : ''}\n`;
    } else {
      // MRS 1.x generation: `all` hangs directly off the elf
      t += `\n# All Target\nall: ${elfTarget}${hasSecondaries ? ' secondary-outputs' : ''}\n`;
    }
    // echo the announce the user typed on the Build Steps page (MRS2 emits
    // the same property); the CDT default applies when it's unset
    if (pre) t += `\t-@echo ${cp.prebuildAnnounce || 'Executing pre-build steps'}\n\t-${pre}\n`;
    if (post) t += `\t-@echo ${cp.postbuildAnnounce || 'Executing post-build steps'}\n\t-${post}\n`;
    t += `\n# Tool invocations\n`;

    if (isExe) {
      t += `${elfTarget}: $(OBJS) $(USER_OBJS)\n`;
      if (mrs2Style) {
        // 2.x: single @ prefix, no tail line
        t += `\t@\t${linker}${common}${ldOpts} -o "${elfTarget}" $(OBJS) $(USER_OBJS) $(LIBS)\n`;
      } else {
        t += `\t@\t@\t${linker}${common}${ldOpts} -o "${elfTarget}" $(OBJS) $(USER_OBJS) $(LIBS)\n`;
        t += `\t@\t@\n`;
      }
      if (flashVar) {
        const copyOpts = objCopyOptions(cp);
        for (const ext of flashExts) {
          const objcopyFlag = ext === 'bin' ? '-O binary' : '-O ihex';
          t += `${target}.${ext}: ${elfTarget}\n`;
          // 1.9.2 keeps the golden's double space between the arguments;
          // 2.x emits a single one; 2.x has no tail line
          t += mrs2Style
            ? `\t@\t${objcopy} ${objcopyFlag}${copyOpts} "${elfTarget}" "${target}.${ext}"\n`
            : `\t@\t${objcopy} ${objcopyFlag}${copyOpts} "${elfTarget}"  "${target}.${ext}"\n`;
          if (!mrs2Style) t += `\t@\t@\n`;
        }
      }
      if (listVar) {
        t += `${target}.lst: ${elfTarget}\n`;
        t += `\t@\t${objdump}${listingOptions(cp)} "${elfTarget}" > "${target}.lst"\n`;
        if (!mrs2Style) t += `\t@\t@\n`;
      }
      if (sizeVar) {
        const fmt = cp.optionEnum('printsize.format') ?? 'berkeley';
        let szFlags = `--format=${fmt}`;
        if (cp.optionBool('printsize.hex')) szFlags += ' -x';
        if (cp.optionBool('printsize.totals')) szFlags += ' --totals';
        const szOther = cp.optionValue('printsize.other')?.trim();
        if (szOther) szFlags += ` ${szOther}`;
        t += `${target}.siz: ${elfTarget}\n`;
        if (mrs2Style) {
          // 2.x: no @ on the size line (it echoes in the build output —
          // visible in MRS2's own build records) and the tail is an empty line
          t += `\t${sizeTool} ${szFlags} "${elfTarget}"\n\n`;
        } else {
          t += `\t@\t${sizeTool} ${szFlags} "${elfTarget}"\n`;
          t += `\t@\t@\n`;
        }
      }
    } else {
      t += `${target}.a: $(OBJS) $(USER_OBJS)\n`;
      t += `\t@\t@\t${ar} -cr "${target}.a" $(OBJS) $(USER_OBJS)\n`;
      t += `\t@\t@\n`;
    }

    // C projects: byte-identical to the MRS2 golden clean line; C++ adds
    // the C++ dep-file variables the golden C order never had. The 2.x
    // golden leads with $(OBJS) and orders the dep groups S_DEPS-first.
    const cleanVars = isCpp
      ? mrs2Style
        ? '$(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(S_DEPS)$(S_UPPER_DEPS)$(ASM_DEPS)$(ASM_UPPER_DEPS)$(C_DEPS)$(C_UPPER_DEPS)$(CPP_DEPS)$(CXX_DEPS)$(CC_DEPS)$(C++_DEPS)'
        : '$(ASM_UPPER_DEPS)$(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(C_UPPER_DEPS)$(CPP_DEPS)$(CXX_DEPS)$(CC_DEPS)$(C++_DEPS)'
      : mrs2Style
        ? '$(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(S_DEPS)$(S_UPPER_DEPS)$(ASM_DEPS)$(ASM_UPPER_DEPS)$(C_DEPS)'
        : '$(ASM_UPPER_DEPS)$(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS)';
    t += `# Other Targets\nclean:\n\t-$(RM) ${cleanVars} ${target}.${isExe ? elfExt : 'a'}\n`;
    // 2.x golden: the clean tail is an empty line, not "\t-@"
    t += mrs2Style ? `\n` : `\t-@\n`;
    if (hasSecondaries) {
      const secs = [
        flashVar ? '$(SECONDARY_FLASH)' : '',
        listVar ? '$(SECONDARY_LIST)' : '',
        sizeVar ? '$(SECONDARY_SIZE)' : '',
      ].filter(Boolean);
      t += `secondary-outputs: ${secs.join(' ')}\n`;
    }
    t += `\n.PHONY: all clean dependents\n\n-include ../makefile.targets`;
    // 2.x golden ends the file right after the targets include — no newline
    if (!mrs2Style) t += '\n';
    writeMk('makefile', t);
  }

  return { files: written, dirs: dirsAsc, sourceCount };
}

function stripExt(logicName: string): string {
  const slash = logicName.lastIndexOf('/');
  const dot = logicName.lastIndexOf('.');
  if (dot > slash) return logicName.slice(0, dot);
  return logicName;
}
